#!/bin/bash -eu

# Create temporary data directory and setup it for all tests.
TEST_ENVS_TMPDIR="$(mktemp -dqt pyvenv_activate_envs_tmpdir.XXXXXX)" || exit 1
export TEST_ENVS_TMPDIR

clean_up_test_envs_tmpdir() {
    local res=$?
    rm -rf "$TEST_ENVS_TMPDIR"
    trap - EXIT
    exit $res
}

trap 'clean_up_test_envs_tmpdir' EXIT INT HUP


# Set current dir to test dir and run test_runner with correct lib path
cd -- "$(dirname "${BASH_SOURCE[0]}")"
export LIB_DIR="./shunit2/lib"
./shunit2/test_runner "$@"
