#!/bin/sh
# Disable unused variable.
#   shellcheck disable=SC2034
# Disable source following.
#   shellcheck disable=SC1090,SC1091

# {{{ Check test variables

if [ -z "${TEST_SCRIPT:-}" ]; then
    echo "\$TEST_SCRIPT not set" >&2
    exit 1
fi

if [ -z "${TEST_DIR:-}" ]; then
    echo "\$TEST_DIR not set" >&2
    exit 1
fi

if [ "$TEST_DIR" != "$(dirname -- "$TEST_SCRIPT")" ]; then
    echo "\$TEST_DIR is not valid, expected $(dirname -- "$TEST_SCRIPT")" \
         ", got $TEST_DIR" >&2
    exit 1
fi

# }}}
# {{{ Source pipenv-activate.sh

. "$TEST_DIR/../pipenv-activate.sh"

# }}}
# {{{ Set common variables and options

# Use absolute path for SHUNIT_PARENT
SHUNIT_PARENT="$(cd -P -- "$TEST_DIR" \
    && printf '%s\n' \
    "$(pwd -P)/$(basename -- "$TEST_SCRIPT")")"


# Set shwordsplit for zsh
[ -n "${ZSH_VERSION:-}" ] && setopt shwordsplit


# }}}
# {{{ Setup pipenv environments


# Use all default Pipenv environment variables.
unset PIPENV_CACHE_DIR
unset PIPENV_COLORBLIND
unset PIPENV_DEFAULT_PYTHON_VERSION
unset PIPENV_DONT_LOAD_ENV
unset PIPENV_DONT_USE_ASDF
unset PIPENV_DONT_USE_PYENV
unset PIPENV_DOTENV_LOCATION
unset PIPENV_EMULATOR
unset PIPENV_HIDE_EMOJIS
unset PIPENV_IGNORE_VIRTUALENVS
unset PIPENV_INSTALL_TIMEOUT
unset PIPENV_MAX_DEPTH
unset PIPENV_MAX_RETRIES
unset PIPENV_MAX_ROUNDS
unset PIPENV_MAX_SUBPROCESS
unset PIPENV_NOSPIN
unset PIPENV_NO_INHERIT
unset PIPENV_PIPFILE
unset PIPENV_PYPI_MIRROR
unset PIPENV_RESOLVE_VCS
unset PIPENV_SHELL
unset PIPENV_SHELL_FANCY
unset PIPENV_SKIP_LOCK
unset PIPENV_SPINNER
unset PIPENV_TIMEOUT
unset PIPENV_VENV_IN_PROJECT
unset PIPENV_YES

# Except these ones.
export PIPENV_IGNORE_VIRTUALENVS=1
export PIPENV_VENV_IN_PROJECT=1


th_setup_envs_tmpdir() {
    echo "Setting up pipenv environments temporary directory" >&2

    th_start_pwd_="$(pwd -P)"
    cp -R -- "$TEST_DIR/envs/." "$TEST_ENVS_TMPDIR"
    for th_env_ in "$TEST_ENVS_TMPDIR"/*; do
        cd -- "$th_env_" || return 1
        pipenv install || return 1
        cd -- "$th_start_pwd_" || return 1
    done

    touch "$TEST_ENVS_TMPDIR/.setup"
    echo
    unset th_env_
}

# }}}
# {{{ Default setup/teardown functions

th_oneTimeSetUp() {
    TEST_START_PWD="$(pwd -P)"

    if [ -z "$TEST_ENVS_TMPDIR" ]; then
        TEST_ENVS_TMPDIR="$SHUNIT_TMPDIR/envs"
        mkdir -- "$TEST_ENVS_TMPDIR"
    fi

    if ! [ -f "$TEST_ENVS_TMPDIR/.setup" ]; then
        th_setup_envs_tmpdir
    fi
}
oneTimeSetUp() {
    th_oneTimeSetUp
}


th_oneTimeTearDown() {
    :
}
oneTimeTearDown() {
    th_oneTimeTearDown
}


th_setUp() {
    # Get back to tmpdir every time we start or exit test to provide
    # consistency.
    cd -- "$TEST_START_PWD" || return 1
}
setUp() {
    th_setUp
}


th_tearDown() {
    th_setUp
}
tearDown() {
    th_tearDown
}

# }}}
