# To test it locally, use `act`: https://github.com/nektos/act

name: Tests
on: [push]
jobs:

  tests:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-12
          - macos-13
        python-version:
          - '3.9'
          - '3.12'
        include:
          - os: ubuntu-20.04
            python-version: 3.6

    runs-on: ${{ matrix.os }}
    name: tests - ${{ matrix.os }} - ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install shells on linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update -y
          sudo apt install -y ksh mksh zsh
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install shells on mac
        if: runner.os == 'macOS'
        run: |
          brew install ksh mksh zsh

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install pipenv
        run: python -m pip install pipenv

      - name: Run checks
        run: ./tests/run_all_tests


  shellCheck:
    runs-on: ubuntu-latest
    name: ShellCheck
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install ShellCheck
        run: |
          sudo apt update -y
          sudo apt install -y shellcheck
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Run sources through ShellCheck
        run: |
          shellcheck pyvenv-activate.sh tests/run_all_tests tests/*_test.sh tests/test_helpers
